MODEL_STARTUP_TIMEOUT_SEC = 30.0 # 各モデルの wait_ready 共通タイムアウト秒数
FULL_FOREGROUND_WAIT_TIMEOUT_SEC = 600.0 # 全前景抽出（Detectron2 で全フレーム処理）の完了待ち

DETECTRON2_SCORE_THRESH = 0.5
DETECTRON2_MAX_DETECTIONS = 5      # 検出数の上限（area 降順で上位）
DETECTRON2_MIN_AREA_RATIO = 0.001  # 画像面積の 0.1% 未満は誤検出として弾く
DETECTRON2_IOU_WITH_TARGET = 0.3   # 対象前景との IoU がこれを超えた検出は対象本人として除外

CASPER_NUM_INFERENCE_STEPS = 1
CASPER_TEMPORAL_WINDOW_SIZE = 21
